### ISSUE TITLE
Extra Metadata Loader logos overlap details section when aligned to bottom

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/DH_Themes#1]
Extra Metadata Loader logos overlap details section when aligned to bottom

![image](https://user-images.githubusercontent.com/1389286/134093193-10665d03-1c09-4447-b349-78d3e25d840e.png)

**Comment by felixkmh** [comment]
fixed via 6617da00d65ae064cddb9c45cce272c4a2dfa3b7
