### ISSUE TITLE
Legendary Epic Launcher

### ISSUE THREAD

**Issue by Linx-ESP** [felixkmh/DH_Themes#14]
![image](https://github.com/felixkmh/DH_Themes/assets/51830853/5fa2be6d-0769-4e2f-aa47-9658f82671d3)
![image](https://github.com/felixkmh/DH_Themes/assets/51830853/c69cd8cd-40df-4a7c-a17c-d27616d28c36)
When using [Legendary ](https://github.com/derrod/legendary)and the playnite integration, games show PC GAME under the cover instead of Epic.

**Comment by felixkmh** [comment]
Done via https://github.com/felixkmh/DH_Themes/pull/15
