### ISSUE TITLE
All popups are blurry

### ISSUE THREAD

**Issue by darklinkpower** [felixkmh/DH_Themes#2]
I noticed that certain popups, like the main menu are blurry for me, probably caused by some element used in them. This is very noticeable in the text.

Screenshots: 

Right click menu looks fine (For comparison): 

The following ones are blurry:

![image](https://user-images.githubusercontent.com/1389286/137716518-0ccebb86-aee0-4d93-bb03-1267a8f09924.png)

![image](https://user-images.githubusercontent.com/1389286/137716385-7a9b64e7-71b1-4c1a-b383-8eefe564d2a7.png)

![image](https://user-images.githubusercontent.com/1389286/137716602-68081f75-e7bf-4013-a15d-86a015f52b29.png)

![image](https://user-images.githubusercontent.com/1389286/137716745-d9a49cbf-e32d-4ff0-bd3a-925bf9701064.png)

![image](https://user-images.githubusercontent.com/1389286/137716781-fc8533df-0a07-4263-b468-e0b02dc6ef33.png)

**Comment by felixkmh** [comment]
It is just the background image that has the noise backed into it, so I don't think that is causing it. Do you by any chance run a High DPI display with scaling? That might have something to do with it, but I don't understand why it does not happen to the game menu as well.

**Comment by darklinkpower** [comment]
Also I made a mistake in the first message. This one doesn't look blurred, it's the grid view right click sub menu
![image](https://user-images.githubusercontent.com/1389286/137893090-9345015a-425c-49db-89bc-3c247225358e.png)
