### ISSUE TITLE
Feature Request: Option to not mute video audio

### ISSUE THREAD

**Issue by AudioDuplication** [felixkmh/DH_Themes#6]
I would very much like it, if there was an option to always have the video audio be audible (not muted). If I need to edit some file using notepad to accomplish this that would work for me.

Side note: I love the theme, its basically perfect for my usecase!

**Comment by felixkmh** [comment]
So I assume you are talking about the fullscreen theme, right?
If so, you can set the volume to a value between 0 and 1 here: https://github.com/felixkmh/DH_Themes/blob/58f80a064a78c8e8f772b78ffcdf3a4c8621bd0f/source/Blur/Views/GameDetails.xaml#L58

**Comment by AudioDuplication** [comment]
Thanks it worked. Yes sorry it relating to fullscreen.

I also had to change the following values, otherwise it would re-mute itself if you scrolled down.

<DoubleAnimation Storyboard.TargetName="VideoTrailer"
                                                         Storyboard.TargetProperty="Volume"
                                                         Duration="1:1" To="1" />
                                                         
<DoubleAnimation Storyboard.TargetName="VideoTrailer"
                                                         Storyboard.TargetProperty="Volume"
                                                         Duration="1:1" To="1" />
