### ISSUE TITLE
Question: Video in fullscreen is zoomed in

### ISSUE THREAD

**Issue by AudioDuplication** [felixkmh/DH_Themes#7]
Once again, thanks for this great theme and your help with it! The big video player is really what makes it shine for me..
I showed a little appreciation through your Ko-Fi. 

I noticed that the video thats playing in fullscreen is zoomed in quite a bit, it makes it so subtitles in videos and other elements of the video are not visible. Is this intentional, and can I change this somehow?

Thanks!

**Comment by AudioDuplication** [comment]
Decided to add a screenshot in case I failed to describe my question properly.
In fullscreen mode:
![image](https://user-images.githubusercontent.com/108935890/181743702-6610ea3a-6f68-4da7-8ba6-4af67e9f60e1.png)

The actual video itself:
![image](https://user-images.githubusercontent.com/108935890/181743866-2770b480-c44d-4f7a-a71b-0aeca74b5479.png)

**Comment by felixkmh** [comment]
Thanks for the support :D Setting this to "Uniform" instead of "UniformToFill" should do it: https://github.com/felixkmh/DH_Themes/blob/58f80a064a78c8e8f772b78ffcdf3a4c8621bd0f/source/Blur/Views/GameDetails.xaml#L53

**Comment by AudioDuplication** [comment]
Thanks it works! Now that I realize what its actually doing it kinda makes sense, probably looks better to most people.

**Comment by felixkmh** [comment]
You could also try setting VerticalAlignment to "Bottom": https://github.com/felixkmh/DH_Themes/blob/58f80a064a78c8e8f772b78ffcdf3a4c8621bd0f/source/Blur/Views/GameDetails.xaml#L54
And leave Stretch at "UniformToFill", at least you should see the bottom of the video completely, if you want to see subtitles.
